var k;k||=typeof Module != 'undefined' ? Module : {};var aa=globalThis.document?.currentScript?.src,ba="",ca;try{ba=(new URL(".",aa)).href}catch{}ca=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);};var da=console.log.bind(console),n=console.error.bind(console),p=!1,ea;function fa(){var a=k.preRun;a&&(typeof a=="function"&&(a=[a]),ha.push(...a));for(a=ha;a.length>0;)a.shift()(k)}
function ia(){var a=k.postRun;a&&(typeof a=="function"&&(a=[a]),ja.push(...a));for(a=ja;a.length>0;)a.shift()(k)}function ka(a){k.onAbort?.(a);a=`Aborted(${a})`;n(a);p=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var la;async function ma(a){try{var b=await ca(a);return new Uint8Array(b)}catch{}throw"both async and sync fetching of the wasm failed";}
async function na(a,b){try{var c=await ma(a);return await WebAssembly.instantiate(c,b)}catch(d){n(`failed to asynchronously prepare wasm: ${d}`),ka(d)}}async function oa(a){var b=la;try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){n(`wasm streaming compile failed: ${d}`),n("falling back to ArrayBuffer instantiation")}return na(b,a)}class pa{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var ja=[],ha=[],qa=!0,q,r=()=>{var a=q[+ra>>2];ra+=4;return a},sa=(a,b)=>{for(var c=0,d=a.length-1;d>=0;d--){var e=a[d];e==="."?a.splice(d,1):e===".."?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},ta=a=>{var b=a.charAt(0)==="/",c=a.slice(-1)==="/";(a=sa(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},ua=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";
b&&=b.slice(0,-1);return a+b},va=a=>a&&a.match(/([^\/]+|\/)\/*$/)[1],wa=()=>a=>(crypto.getRandomValues(a),0),xa=a=>(xa=wa())(a),ya=(...a)=>{for(var b="",c=!1,d=a.length-1;d>=-1&&!c;d--){c=d>=0?a[d]:"/";if(typeof c!="string")throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c=c.charAt(0)==="/"}b=sa(b.split("/").filter(e=>!!e),!c).join("/");return(c?"/":"")+b||"."},za=globalThis.TextDecoder&&new TextDecoder,t=(a,b=0,c)=>{var d=b;for(c=d+c;a[d]&&!(d>=c);)++d;if(d-
b>16&&a.buffer&&za)return za.decode(a.subarray(b,d));for(c="";b<d;){var e=a[b++];if(e&128){var f=a[b++]&63;if((e&224)==192)c+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;e=(e&240)==224?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;e<65536?c+=String.fromCharCode(e):(e-=65536,c+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else c+=String.fromCharCode(e)}return c},Aa=[],u=(a,b,c,d)=>{if(!(d>0))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.codePointAt(f);if(g<=127){if(c>=
d)break;b[c++]=g}else if(g<=2047){if(c+1>=d)break;b[c++]=192|g>>6;b[c++]=128|g&63}else if(g<=65535){if(c+2>=d)break;b[c++]=224|g>>12;b[c++]=128|g>>6&63;b[c++]=128|g&63}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63;b[c++]=128|g>>6&63;b[c++]=128|g&63;f++}}b[c]=0;return c-e},Ba=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);d<=127?b++:d<=2047?b+=2:d>=55296&&d<=57343?(b+=4,++c):b+=3}b=Array(b+1);a=u(a,b,0,b.length);b.length=a;return b},Ca=[];
function Da(a,b){Ca[a]={input:[],output:[],$a:b};Ea(a,Fa)}
var Fa={open(a){var b=Ca[a.node.Hb];if(!b)throw new v(43);a.Qa=b;a.seekable=!1},close(a){a.Qa.$a.Ab(a.Qa)},Ab(a){a.Qa.$a.Ab(a.Qa)},read(a,b,c,d){if(!a.Qa||!a.Qa.$a.dc)throw new v(60);for(var e=0,f=0;f<d;f++){try{var g=a.Qa.$a.dc(a.Qa)}catch(h){throw new v(29);}if(g===void 0&&!e)throw new v(6);if(g===null||g===void 0)break;e++;b[c+f]=g;if(g===10)break}e&&(a.node.bb=Date.now());return e},write(a,b,c,d){if(!a.Qa||!a.Qa.$a.Qb)throw new v(60);try{for(var e=0;e<d;e++)a.Qa.$a.Qb(a.Qa,b[c+e])}catch(f){throw new v(29);
}d&&(a.node.Sa=a.node.Va=Date.now());return e}},Ga={dc(){a:{if(!Aa.length){var a=null;globalThis.window?.prompt&&(a=window.prompt("Input: "),a!==null&&(a+="\n"));if(!a){a=null;break a}Aa=Ba(a)}a=Aa.shift()}return a},Qb(a,b){b===null||b===10?(da(t(a.output)),a.output=[]):b!=0&&a.output.push(b)},Ab(a){a.output?.length>0&&(da(t(a.output)),a.output=[])},Fc(){return{bd:25856,dd:5,ad:191,cd:35387,$c:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},Gc(){return 0},Hc(){return[24,
80]}},Ha={Qb(a,b){b===null||b===10?(n(t(a.output)),a.output=[]):b!=0&&a.output.push(b)},Ab(a){a.output?.length>0&&(n(t(a.output)),a.output=[])}},z,A={Ya:null,Ra(){return A.createNode(null,"/",16895,0)},createNode(a,b,c,d){if((c&61440)===24576||(c&61440)===4096)throw new v(63);A.Ya||(A.Ya={dir:{node:{Za:A.Na.Za,ab:A.Na.ab,sb:A.Na.sb,kb:A.Na.kb,Jb:A.Na.Jb,qb:A.Na.qb,ob:A.Na.ob,Ib:A.Na.Ib,pb:A.Na.pb},stream:{Xa:A.Oa.Xa}},file:{node:{Za:A.Na.Za,ab:A.Na.ab},stream:{Xa:A.Oa.Xa,read:A.Oa.read,write:A.Oa.write,
hc:A.Oa.hc,kc:A.Oa.kc}},link:{node:{Za:A.Na.Za,ab:A.Na.ab,ub:A.Na.ub},stream:{}},Zb:{node:{Za:A.Na.Za,ab:A.Na.ab},stream:Ja}});c=Ka(a,b,c,d);B(c.mode)?(c.Na=A.Ya.dir.node,c.Oa=A.Ya.dir.stream,c.Pa={}):(c.mode&61440)===32768?(c.Na=A.Ya.file.node,c.Oa=A.Ya.file.stream,c.Ta=0,c.Pa=A.wc??(A.wc=new Uint8Array(0))):(c.mode&61440)===40960?(c.Na=A.Ya.link.node,c.Oa=A.Ya.link.stream):(c.mode&61440)===8192&&(c.Na=A.Ya.Zb.node,c.Oa=A.Ya.Zb.stream);c.bb=c.Sa=c.Va=Date.now();a&&(a.Pa[b]=c,a.bb=a.Sa=a.Va=c.bb);
return c},Na:{Za(a){var b={};b.gd=(a.mode&61440)===8192?a.id:1;b.ud=a.id;b.mode=a.mode;b.yd=1;b.uid=0;b.td=0;b.Hb=a.Hb;B(a.mode)?b.size=4096:(a.mode&61440)===32768?b.size=a.Ta:(a.mode&61440)===40960?b.size=a.link.length:b.size=0;b.bb=new Date(a.bb);b.Sa=new Date(a.Sa);b.Va=new Date(a.Va);b.rc=4096;b.Zc=Math.ceil(b.size/b.rc);return b},ab(a,b){for(var c of["mode","atime","mtime","ctime"])b[c]!=null&&(a[c]=b[c]);b.size!==void 0&&(b=b.size,a.Ta!=b&&(c=a.Pa,a.Pa=new Uint8Array(b),a.Pa.set(c.subarray(0,
Math.min(b,a.Ta))),a.Ta=b))},sb(){A.Kb||(A.Kb=new v(44),A.Kb.stack="<generic error, no stack>");throw A.Kb;},kb(a,b,c,d){return A.createNode(a,b,c,d)},Jb(a,b,c){try{var d=C(b,c)}catch(f){}if(d){if(B(a.mode))for(var e in d.Pa)throw new v(55);La(d)}delete a.parent.Pa[a.name];b.Pa[c]=a;a.name=c;b.Va=b.Sa=a.parent.Va=a.parent.Sa=Date.now()},qb(a,b){delete a.Pa[b];a.Va=a.Sa=Date.now()},ob(a,b){var c=C(a,b),d;for(d in c.Pa)throw new v(55);delete a.Pa[b];a.Va=a.Sa=Date.now()},Ib(a){return[".","..",...Object.keys(a.Pa)]},
pb(a,b,c){a=A.createNode(a,b,41471,0);a.link=c;return a},ub(a){if((a.mode&61440)!==40960)throw new v(28);return a.link}},Oa:{read(a,b,c,d,e){if(e>=a.node.Ta)return 0;d=Math.min(a.node.Ta-e,d);b.set(a.node.Pa.subarray(e,e+d),c);return d},write(a,b,c,d,e,f){if(!d)return 0;a=a.node;a.Sa=a.Va=Date.now();if(f)a.Pa=b.subarray(c,c+d),a.Ta=d;else if(a.Ta||e){f=e+d;var g=a.Pa.length;g>=f||(f=Math.max(f,g*(g<1048576?2:1.125)>>>0),g&&(f=Math.max(f,256)),g=a.Pa.subarray(0,a.Ta),a.Pa=new Uint8Array(f),a.Pa.set(g));
a.Pa.set(b.subarray(c,c+d),e);a.Ta=Math.max(a.Ta,e+d)}else a.Pa=b.slice(c,c+d),a.Ta=d;return d},Xa(a,b,c){c===1?b+=a.position:c===2&&(a.node.mode&61440)===32768&&(b+=a.node.Ta);if(b<0)throw new v(28);return b},hc(a,b,c,d,e){if((a.node.mode&61440)!==32768)throw new v(43);a=a.node.Pa;if(e&2||a.buffer!==z.buffer){d=!0;ka();e=void 0;if(!e)throw new v(48);if(a){if(c>0||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);z.set(a,e)}}else d=!1,e=a.byteOffset;return{Bd:e,Wc:d}},
kc(a,b,c,d){A.Oa.write(a,b,0,d,c,!1);return 0}}},Ma=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},D={zb:{},indexedDB:()=>indexedDB,oc:21,gb:"FILE_DATA",nb:a=>{function b(){a.hb==="again"?c():(a.hb=0,D.Nc?.(!1))}function c(){a.hb="idb";D.Nc?.(!0);D.Rb(a,!1,b)}a.hb?a.hb==="idb"&&(a.hb="again"):a.hb=setTimeout(c,0)},Ra:a=>{var b=A.Ra(a);if(a?.Oc?.qc){a.hb=0;var c=b.Na;b.Na={...b.Na};b.Na.kb=(d,e,f,g)=>{var h=c.kb(d,e,f,g);h.Na=b.Na;h.Cc=b.Ra;h.Ob=h.Oa;h.Oa={...h.Oa};h.Oa.write=(m,l,w,x,y,L)=>{m.node.ec=
!0;return h.Ob.write(m,l,w,x,y,L)};h.Oa.close=m=>{var l=m.node;l.ec&&(D.nb(l.Cc),l.ec=!1);if(l.Ob.close)return l.Ob.close(m)};D.nb(b.Ra);return h};b.Na.ob=(...d)=>(D.nb(b.Ra),c.ob(...d));b.Na.pb=(...d)=>(D.nb(b.Ra),c.pb(...d));b.Na.qb=(...d)=>(D.nb(b.Ra),c.qb(...d));b.Na.Jb=(...d)=>(D.nb(b.Ra),c.Jb(...d))}return b},Rb:(a,b,c)=>{D.Ac(a,(d,e)=>{if(d)return c(d);D.Bc(a,(f,g)=>{if(f)return c(f);D.Pc(b?g:e,b?e:g,c)})})},Cd:()=>{for(var a of Object.values(D.zb))a.close();D.zb={}},zc:(a,b)=>{var c=D.zb[a];
if(c)return b(null,c);try{var d=D.indexedDB().open(a,D.oc)}catch(e){return b(e)}if(!d)return b("Unable to connect to IndexedDB");d.onupgradeneeded=e=>{var f=e.target.result;e=e.target.transaction;var g;f.objectStoreNames.contains(D.gb)?g=e.objectStore(D.gb):g=f.createObjectStore(D.gb);g.indexNames.contains("timestamp")||g.createIndex("timestamp","timestamp",{unique:!1})};d.onsuccess=()=>{c=d.result;D.zb[a]=c;b(null,c)};d.onerror=e=>{b(e.target.error);e.preventDefault()}},Ac:(a,b)=>{function c(h){return h!==
"."&&h!==".."}function d(h){return m=>ta(h+"/"+m)}var e={};for(a=Na(a.tb).filter(c).map(d(a.tb));a.length;){var f=a.pop();try{var g=Oa(f)}catch(h){return b(h)}B(g.mode)&&a.push(...Na(f).filter(c).map(d(f)));e[f]={timestamp:g.Sa}}return b(null,{type:"local",entries:e})},Bc:(a,b)=>{var c={};D.zc(a.tb,(d,e)=>{if(d)return b(d);try{var f=e.transaction([D.gb],"readonly");f.onerror=g=>{b(g.target.error);g.preventDefault()};f.objectStore(D.gb).index("timestamp").openKeyCursor().onsuccess=g=>{g=g.target.result;
if(!g)return b(null,{type:"remote",db:e,entries:c});c[g.primaryKey]={timestamp:g.key};g.continue()}}catch(g){return b(g)}})},Ic:(a,b)=>{try{var c=E(a).node;var d=Oa(a)}catch(e){return b(e)}return B(d.mode)?b(null,{timestamp:d.Sa,mode:d.mode}):(d.mode&61440)===40960?b(null,{timestamp:d.Sa,mode:d.mode,link:c.link}):(d.mode&61440)===32768?(c.Pa=c.Pa.subarray(0,c.Ta),b(null,{timestamp:d.Sa,mode:d.mode,contents:c.Pa})):b(Error("node type not supported"))},Sc:(a,b,c)=>{try{if(B(b.mode)){var d=b.mode,e=
a.split("/"),f="",g;for(g of e)if(g){if(f||a.charAt(0)==="/")f+="/";f+=g;try{F(f,d)}catch(x){if(x.Wa!=20)throw x;}}}else if((b.mode&61440)===40960)Pa(b.link,a);else if((b.mode&61440)===32768){f=b.contents;d={sc:!0};d.flags=d.flags??577;var h=Qa(a,d.flags,d.mode);e=f;typeof e=="string"&&(e=Ba(e));e.subarray||(e=new Uint8Array(e));f=e;Ra(h,f,0,f.byteLength,d.sc);Sa(h)}else return c(Error("node type not supported"));Ta(a,b.mode);var m=b.timestamp,l=b.timestamp,w=E(a,{jb:!0});Ua(w.node,{bb:m,Sa:l,vc:void 0})}catch(x){return c(x)}c(null)},
Qc:(a,b)=>{try{var c=Oa(a);if(B(c.mode)){var d=E(a,{parent:!0}).node,e=va(a),f=C(d,e),g=Va(d,e,!0);if(g)throw new v(g);if(!d.Na.ob)throw new v(63);if(f.lb)throw new v(10);d.Na.ob(d,e);La(f)}else{var h=E(a,{parent:!0}).node;if(!h)throw new v(44);var m=va(a),l=C(h,m),w=Va(h,m,!1);if(w)throw new v(w);if(!h.Na.qb)throw new v(63);if(l.lb)throw new v(10);h.Na.qb(h,m);La(l)}}catch(x){return b(x)}b(null)},Jc:(a,b,c)=>{a=a.get(b);a.onsuccess=d=>c(null,d.target.result);a.onerror=d=>{c(d.target.error);d.preventDefault()}},
Tc:(a,b,c,d)=>{try{var e=a.put(c,b)}catch(f){d(f);return}e.onsuccess=()=>d();e.onerror=f=>{d(f.target.error);f.preventDefault()}},Rc:(a,b,c)=>{a=a.delete(b);a.onsuccess=()=>c();a.onerror=d=>{c(d.target.error);d.preventDefault()}},Pc:(a,b,c)=>{function d(y){if(y&&!l)return l=!0,c(y)}var e=0,f=[],g;for([g,m]of Object.entries(a.entries)){var h=b.entries[g];h&&m.timestamp.getTime()==h.timestamp.getTime()||(f.push(g),e++)}var m=[];for(g of Object.keys(b.entries))a.entries[g]||(m.push(g),e++);if(!e)return c(null);
var l=!1;a=(a.type==="remote"?a.db:b.db).transaction([D.gb],"readwrite");var w=a.objectStore(D.gb);a.onerror=a.onabort=y=>{d(y.target.error);y.preventDefault()};a.oncomplete=()=>{l||c(null)};for(let y of f.sort())b.type==="local"?D.Jc(w,y,(L,X)=>{if(L)return d(L);D.Sc(y,X,d)}):D.Ic(y,(L,X)=>{if(L)return d(L);D.Tc(w,y,X,d)});for(var x of m.sort().reverse())b.type==="local"?D.Qc(x,d):D.Rc(w,x,d)}},Wa=null,Xa={},G=[],Ya=1,H=null,Za=!1,$a=!0,ab=0,v=class{name="ErrnoError";constructor(a){this.Wa=a}},bb=
class{shared={};node=null;get flags(){return this.shared.flags}set flags(a){this.shared.flags=a}get position(){return this.shared.position}set position(a){this.shared.position=a}},cb=class{Na={};Oa={};lb=null;constructor(a,b,c,d){a||=this;this.parent=a;this.Ra=a.Ra;this.id=Ya++;this.name=b;this.mode=c;this.Hb=d;this.bb=this.Sa=this.Va=Date.now()}get read(){return(this.mode&365)===365}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return(this.mode&146)===146}set write(a){a?this.mode|=146:
this.mode&=-147}Mc(){}};
function E(a,b={}){if(!a)throw new v(44);b.Lb??(b.Lb=!0);a.charAt(0)==="/"||(a="//"+a);var c=0;a:for(;c<40;c++){a=a.split("/").filter(h=>!!h);for(var d=Wa,e="/",f=0;f<a.length;f++){var g=f===a.length-1;if(g&&b.parent)break;if(a[f]!==".")if(a[f]==="..")if(e=ua(e),d===d.parent){a=e+"/"+a.slice(f+1).join("/");c--;continue a}else d=d.parent;else{e=ta(e+"/"+a[f]);try{d=C(d,a[f])}catch(h){if(h?.Wa===44&&g&&b.Lc)return{path:e};throw h;}!d.lb||g&&!b.Lb||(d=d.lb.root);if((d.mode&61440)===40960&&(!g||b.jb)){if(!d.Na.ub)throw new v(52);
d=d.Na.ub(d);d.charAt(0)==="/"||(d=ua(e)+"/"+d);a=d+"/"+a.slice(f+1).join("/");continue a}}}return{path:e,node:d}}throw new v(32);}function db(a){for(var b;;){if(a===a.parent)return a=a.Ra.tb,b?a[a.length-1]!=="/"?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function eb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%H.length}function La(a){var b=eb(a.parent.id,a.name);if(H[b]===a)H[b]=a.mb;else for(b=H[b];b;){if(b.mb===a){b.mb=a.mb;break}b=b.mb}}
function C(a,b){var c=B(a.mode)?(c=fb(a,"x"))?c:a.Na.sb?0:2:54;if(c)throw new v(c);for(c=H[eb(a.id,b)];c;c=c.mb){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.Na.sb(a,b)}function Ka(a,b,c,d){a=new cb(a,b,c,d);b=eb(a.parent.id,a.name);a.mb=H[b];return H[b]=a}function B(a){return(a&61440)===16384}function fb(a,b){return $a?0:b.includes("r")&&!(a.mode&292)||b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73)?2:0}
function gb(a,b){if(!B(a.mode))return 54;try{return C(a,b),20}catch(c){}return fb(a,"wx")}function Va(a,b,c){try{var d=C(a,b)}catch(e){return e.Wa}if(a=fb(a,"wx"))return a;if(c){if(!B(d.mode))return 54;if(d===d.parent||db(d)==="/")return 10}else if(B(d.mode))return 31;return 0}function hb(a,b){if(!a)throw new v(b);return a}function I(a){a=G[a];if(!a)throw new v(8);return a}
function ib(a,b=-1){a=Object.assign(new bb,a);if(b==-1)a:{for(b=0;b<=4096;b++)if(!G[b])break a;throw new v(33);}a.fb=b;return G[b]=a}function jb(a,b=-1){a=ib(a,b);a.Oa?.ld?.(a);return a}function Ua(a,b){var c=void 0,d=c?null:a;c??=a.Na.ab;hb(c,63);try{c(d,b)}catch(e){if(e instanceof RangeError)throw new v(22);throw e;}}var Ja={open(a){a.Oa=Xa[a.node.Hb].Oa;a.Oa.open?.(a)},Xa(){throw new v(70);}};function Ea(a,b){Xa[a]={Oa:b}}
function kb(){for(var a=[],b=[Wa.Ra];b.length;){var c=b.pop();a.push(c);b.push(...c.jc)}return a}function lb(a){function b(h){ab--;return a(h)}function c(h){if(h){if(!c.xc)return c.xc=!0,b(h)}else++f>=e.length&&b(null)}var d=!0;typeof d=="function"&&(a=d,d=!1);ab++;ab>1&&n(`warning: ${ab} FS.syncfs operations in flight at once, probably just doing extra work`);var e=kb(),f=0,g;for(g of e)g.type.Rb?g.type.Rb(g,d,c):c(null)}
function mb(a,b,c){var d=c==="/";if(d&&Wa)throw new v(10);if(!d&&c){var e=E(c,{Lb:!1});c=e.path;e=e.node;if(e.lb)throw new v(10);if(!B(e.mode))throw new v(54);}b={type:a,Oc:b,tb:c,jc:[]};a=a.Ra(b);a.Ra=b;b.root=a;d?Wa=a:e&&(e.lb=b,e.Ra&&e.Ra.jc.push(b))}function nb(a,b,c){var d=E(a,{parent:!0}).node;a=va(a);if(!a)throw new v(28);if(a==="."||a==="..")throw new v(20);var e=gb(d,a);if(e)throw new v(e);if(!d.Na.kb)throw new v(63);return d.Na.kb(d,a,b,c)}
function F(a,b=511){return nb(a,b&1023|16384,0)}function ob(a,b,c){typeof c=="undefined"&&(c=b,b=438);nb(a,b|8192,c)}function Pa(a,b){if(!ya(a))throw new v(44);var c=E(b,{parent:!0}).node;if(!c)throw new v(44);b=va(b);var d=gb(c,b);if(d)throw new v(d);if(!c.Na.pb)throw new v(63);c.Na.pb(c,b,a)}function Na(a){a=E(a,{jb:!0}).node;return hb(a.Na.Ib,54)(a)}function Oa(a){a=E(a,{jb:!1}).node;return hb(a.Na.Za,63)(a)}
function Ta(a,b){a=typeof a=="string"?E(a,{jb:!0}).node:a;Ua(a,{mode:b&4095|a.mode&-4096,Va:Date.now(),vc:void 0})}
function Qa(a,b,c=438){if(a==="")throw new v(44);if(typeof b=="string"){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if(typeof d=="undefined")throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?c&4095|32768:0;if(typeof a=="object")d=a;else{var e=a.endsWith("/");var f=E(a,{jb:!(b&131072),Lc:!0});d=f.node;a=f.path}f=!1;if(b&64)if(d){if(b&128)throw new v(20);}else{if(e)throw new v(31);d=nb(a,c|511,0);f=!0}if(!d)throw new v(44);(d.mode&61440)===8192&&(b&=-513);if(b&65536&&!B(d.mode))throw new v(54);
if(!f&&(d?(d.mode&61440)===40960?e=32:(e=["r","w","rw"][b&3],b&512&&(e+="w"),e=B(d.mode)&&(e!=="r"||b&576)?31:fb(d,e)):e=44,e))throw new v(e);if(b&512&&!f){e=d;e=typeof e=="string"?E(e,{jb:!0}).node:e;if(B(e.mode))throw new v(31);if((e.mode&61440)!==32768)throw new v(28);if(a=fb(e,"w"))throw new v(a);Ua(e,{size:0,timestamp:Date.now()})}b=ib({node:d,path:db(d),flags:b&-131713,seekable:!0,position:0,Oa:d.Oa,Uc:[],error:!1});b.Oa.open&&b.Oa.open(b);f&&Ta(d,c&511);return b}
function Sa(a){if(a.fb===null)throw new v(8);a.Mb&&(a.Mb=null);a.node?.Mc();try{a.Oa.close&&a.Oa.close(a)}catch(b){throw b;}finally{G[a.fb]=null}a.fb=null}function pb(a,b,c){if(a.fb===null)throw new v(8);if(!a.seekable||!a.Oa.Xa)throw new v(70);if(c!=0&&c!=1&&c!=2)throw new v(28);a.position=a.Oa.Xa(a,b,c);a.Uc=[]}
function Ra(a,b,c,d,e){var f=void 0;if(d<0||f<0)throw new v(28);if(a.fb===null)throw new v(8);if((a.flags&2097155)===0)throw new v(8);if(B(a.node.mode))throw new v(31);if(!a.Oa.write)throw new v(28);a.seekable&&a.flags&1024&&pb(a,0,2);var g=typeof f!="undefined";if(!g)f=a.position;else if(!a.seekable)throw new v(70);b=a.Oa.write(a,b,c,d,f,e);g||(a.position+=b);return b}
function qb(){var a,b,c;Za=!0;a??=k.stdin;b??=k.stdout;c??=k.stderr;a?J("stdin",a):Pa("/dev/tty","/dev/stdin");b?J("stdout",null,b):Pa("/dev/tty","/dev/stdout");c?J("stderr",null,c):Pa("/dev/tty1","/dev/stderr");Qa("/dev/stdin",0);Qa("/dev/stdout",1);Qa("/dev/stderr",1)}
function J(a,b,c){a=ta("/dev/"+a);var d=Ma(!!b,!!c);J.fc??(J.fc=64);var e=J.fc++<<8|0;Ea(e,{open(f){f.seekable=!1},close(){c?.buffer?.length&&c(10)},read(f,g,h,m){for(var l=0,w=0;w<m;w++){try{var x=b()}catch(y){throw new v(29);}if(x===void 0&&!l)throw new v(6);if(x===null||x===void 0)break;l++;g[h+w]=x}l&&(f.node.bb=Date.now());return l},write(f,g,h,m){for(var l=0;l<m;l++)try{c(g[h+l])}catch(w){throw new v(29);}m&&(f.node.Sa=f.node.Va=Date.now());return l}});ob(a,d,e)}
var K={},M,N,rb,ra=void 0,O,sb=0,tb={},ub=a=>{if(!(a instanceof pa||a=="unwind"))throw a;},vb=a=>{ea=a;qa||sb>0||(k.onExit?.(a),p=!0);throw new pa(a);},wb=()=>{if(!(qa||sb>0))try{var a=ea;ea=a;vb(a)}catch(b){ub(b)}},xb=a=>{if(!p)try{a()}catch(b){ub(b)}finally{wb()}},yb=[],zb,Ab=a=>{if(a.requestPointerLock)a.requestPointerLock();else return document.body.requestPointerLock?-3:-1;return 0},Bb=[0,document,window],P=a=>{a=a>2?a?t(M,a):"":a;return Bb[a]||document.querySelector(a)};
function Cb(a){var b=Q.Ua[a];b.target.removeEventListener(b.eb,b.cc,b.xb);Q.Ua.splice(a,1)}function Db(a){function b(d,e){if(d.length!=e.length)return!1;for(var f=0;f<d.length;f++)if(d[f]!=e[f])return!1;return!0}for(var c of Q.cb)if(c.Sb==Ab&&b(c.Yb,a))return;Q.cb.push({Sb:Ab,lc:2,Yb:a});Q.cb.sort((d,e)=>d.lc-e.lc)}function Eb(){if(navigator.userActivation?navigator.userActivation.isActive:Q.Cb&&Q.$b.Xb){var a=Q.cb;Q.cb=[];for(var b of a)b.Sb(...b.Yb)}}
function Fb(a){if(!a.target)return-4;if(a.ib)a.cc=function(c){++Q.Cb;Q.$b=a;Eb();a.Bb(c);Eb();--Q.Cb},a.target.addEventListener(a.eb,a.cc,a.xb),Q.Ua.push(a);else for(var b=0;b<Q.Ua.length;++b)Q.Ua[b].target==a.target&&Q.Ua[b].eb==a.eb&&Cb(b--);return 0}
var Q={Yc:0,sd:0,Nb:0,Gb:0,Md:0,Tb:0,pd:0,jd:0,zd:0,hd:0,qd:0,Pb:0,Kd:0,Jd:0,Dd(){for(;Q.Ua.length;)Cb(Q.Ua.length-1);Q.cb=[]},Cb:0,cb:[],Fd(a){Q.cb=Q.cb.filter(b=>b.Sb!=a)},Ua:[],Ed:(a,b)=>{for(var c=0;c<Q.Ua.length;++c)Q.Ua[c].target!=a||b&&b!=Q.Ua[c].eb||Cb(c--)},Gd(a){var b=!1;for(let c=0;c<Q.Ua.length;++c){let d=Q.Ua[c];d.target===a.target&&d.rb===a.rb&&d.ib===a.ib&&d.yb===a.yb&&(Cb(c--),b=!0)}return b?0:-5},fullscreenEnabled(){return document.fullscreenEnabled??document.webkitFullscreenEnabled}},
Hb=(a,b,c,d,e,f)=>{Q.Nb||(Q.Nb=Gb(160));a={target:P(a),eb:f,rb:e,yb:b,ib:d,Bb:g=>{var h=Q.Nb;zb[h>>3]=g.timeStamp;var m=h>>2;q[m+2]=g.location;z[h+12]=g.ctrlKey;z[h+13]=g.shiftKey;z[h+14]=g.altKey;z[h+15]=g.metaKey;z[h+16]=g.repeat;q[m+5]=g.charCode;q[m+6]=g.keyCode;q[m+7]=g.which;u(g.key??"",M,h+32,32);u(g.code??"",M,h+64,32);u(g.char??"",M,h+96,32);u(g.locale??"",M,h+128,32);R.get(d)(e,h,b)&&g.preventDefault()},xb:c};return Fb(a)},Pb=(a,b)=>{Ib=a;Jb=b;if(Kb)if(a==0)T=function(){setTimeout(Lb,Math.max(0,
Mb+b-performance.now())|0)};else if(a==1)T=function(){Nb(Lb)};else{if(!Ob)if(globalThis.scheduler)Ob=scheduler.postTask.bind(scheduler);else{var c=[];addEventListener("message",d=>{d.data==="setimmediate"&&(d.stopPropagation(),c.shift()())},!0);Ob=d=>{c.push(d);postMessage("setimmediate","*")}}T=function(){Ob(Lb)}}},Kb=null,T=null,Qb=0,Rb=0,Ib=0,Jb=0,Sb=0,Tb=[],Ub=[],Vb=[],Wb=0;
function Nb(a){if(globalThis.requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(Wb)for(;b+2>=Wb;)Wb+=1E3/60;else Wb=b+1E3/60;setTimeout(a,Math.max(Wb-b,0))}}
var Xb={},Mb,Lb,Ob,Yb,Zb=(a,b,c,d,e)=>{function f(){return g<Qb?(wb(),!1):!0}Kb=a;Rb=d;var g=Qb;Lb=function(){if(!p)if(Tb.length>0){var h=Tb.shift();h.rd(h.Xc);if(Yb){var m=Yb,l=m%1==0?m-1:Math.floor(m);Yb=h.ed?l:(8*m+(l+.5))/9}k.setStatus&&(h=k.statusMessage||"Please wait...",m=Yb??0,l=Xb.md??0,m?m<l?k.setStatus("{message} ({expected - remaining}/{expected})"):k.setStatus(h):k.setStatus(""));f()&&setTimeout(Lb,0)}else if(f())if(Sb=Sb+1|0,Ib==1&&Jb>1&&Sb%Jb!=0)T();else{Ib==0&&(Mb=performance.now());
a:if(!p){for(h of Ub)if(h()===!1)break a;xb(a);for(m of Vb)m()}f()&&T()}};e||(b>0?Pb(0,1E3/b):Pb(1,1),T());if(c)throw"unwind";},bc=(a,b,c,d,e,f)=>{Q.Gb||(Q.Gb=Gb(64));a=P(a);return Fb({target:a,Xb:f!="mousemove"&&f!="mouseenter"&&f!="mouseleave",eb:f,rb:e,yb:b,ib:d,Bb:g=>{var h=a,m=Q.Gb;zb[m>>3]=g.timeStamp;var l=m>>2;q[l+2]=g.screenX;q[l+3]=g.screenY;q[l+4]=g.clientX;q[l+5]=g.clientY;z[m+24]=g.ctrlKey;z[m+25]=g.shiftKey;z[m+26]=g.altKey;z[m+27]=g.metaKey;O[l*2+14]=g.button;O[l*2+15]=g.buttons;q[l+
8]=g.movementX;q[l+9]=g.movementY;h=Bb.indexOf(h)<0?h.getBoundingClientRect():{left:0,top:0};q[l+10]=g.clientX-(h.left|0);q[l+11]=g.clientY-(h.top|0);R.get(d)(e,Q.Gb,b)&&g.preventDefault()},xb:c})},cc=(a,b,c,d)=>{Q.Pb||(Q.Pb=Gb(257));return Fb({target:a,eb:"pointerlockchange",rb:20,yb:b,ib:d,Bb:e=>{var f=Q.Pb,g=document.pointerLockElement;z[f]=!!g;var h=g?.id??"";u(g==window?"#window":g==screen?"#screen":g?.nodeName??"",M,f+1,128);u(h,M,f+129,128);R.get(d)(20,f,b)&&e.preventDefault()},xb:c})},dc=
(a,b,c,d)=>{Q.Tb||(Q.Tb=Gb(36));a=P(a);return Fb({target:a,eb:"resize",rb:10,yb:b,ib:d,Bb:e=>{if(e.target==a){var f=document.body;if(f){var g=Q.Tb;q[g>>2]=0;q[g+4>>2]=f.clientWidth;q[g+8>>2]=f.clientHeight;q[g+12>>2]=innerWidth;q[g+16>>2]=innerHeight;q[g+20>>2]=outerWidth;q[g+24>>2]=outerHeight;q[g+28>>2]=pageXOffset|0;q[g+32>>2]=pageYOffset|0;R.get(d)(10,g,b)&&e.preventDefault()}}},xb:c})},U,ec=a=>{var b="EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return a.getSupportedExtensions()?.filter(c=>b.includes(c))??[]},fc=1,hc=[],V=[],ic=[],jc=[],kc=[],W=[],lc=[],mc=[],nc=a=>{for(var b=fc++,c=a.length;c<b;c++)a[c]=null;return b},oc=(a,b,c,d)=>{for(var e=0;e<a;e++){var f=U[c](),g=f&&nc(d);f?(f.name=g,d[g]=f):Y||=1282;q[b+e*4>>2]=g}},qc=(a,b)=>{a.Wb||(a.Wb=a.getContext,a.getContext=function(d,e){e=a.Wb(d,e);return d=="webgl"==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl2",b);return c?pc(c,b):0},pc=(a,b)=>{var c=nc(mc),d={handle:c,
attributes:b,version:b.Kc,Vb:a};a.canvas&&(a.canvas.Vc=d);mc[c]=d;if(typeof b.bc=="undefined"||b.bc)if((a=d)||(a=rc),!a.Dc){a.Dc=!0;b=a.Vb;b.xd=b.getExtension("WEBGL_multi_draw");b.od=b.getExtension("EXT_polygon_offset_clamp");b.nd=b.getExtension("EXT_clip_control");b.Ld=b.getExtension("WEBGL_polygon_mode");b.kd=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.vd=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");a.version>=2&&(b.ac=b.getExtension("EXT_disjoint_timer_query_webgl2"));
if(a.version<2||!b.ac)b.ac=b.getExtension("EXT_disjoint_timer_query");for(var e of ec(b))e.includes("lose_context")||e.includes("debug")||b.getExtension(e)}return c},Y,rc,sc=["default","low-power","high-performance"],tc=()=>{var a=ec(U);return a=a.concat(a.map(b=>"GL_"+b))},Z,uc=(a,b)=>{if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:Y||=1280;return;case 34814:case 36345:c=0;break;case 34466:var d=U.getParameter(34467);c=d?d.length:0;break;case 33309:if(rc.version<2){Y||=1282;return}c=
tc().length;break;case 33307:case 33308:if(rc.version<2){Y||=1280;return}c=a==33307?3:0}if(c===void 0)switch(d=U.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":Y||=1280;return;case "object":if(d===null)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=0;break;default:Y||=1280;return}else{if(d instanceof
Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)Z[b+a*4>>2]=d[a];return}try{c=d.name|0}catch(e){Y||=1280;n(`GL_INVALID_ENUM in glGet2v: Unknown object returned from WebGL getParameter(${a})! (error: ${e})`);return}}break;default:Y||=1280;n(`GL_INVALID_ENUM in glGet2v: Native code calling glGet2v(${a}) and it returns ${d} of type ${typeof d}!`);return}Z[b>>2]=c}else Y||=1281},vc=a=>a.slice(-1)=="]"&&a.lastIndexOf("["),wc,xc=a=>{a-=5120;return a==
0?z:a==1?M:a==2?O:a==4?q:a==6?Z:a==5||a==28922||a==28520||a==30779||a==30782?N:wc},yc=a=>{var b=U.uc;if(b){var c=b.wb[a];typeof c=="number"&&(b.wb[a]=c=U.getUniformLocation(b,b.mc[a]+(c>0?`[${c}]`:"")));return c}Y||=1282};H=Array(4096);mb(A,{},"/");F("/tmp");F("/home");F("/home/web_user");
(function(){F("/dev");Ea(259,{read:()=>0,write:(d,e,f,g)=>g,Xa:()=>0});ob("/dev/null",259);Da(1280,Ga);Da(1536,Ha);ob("/dev/tty",1280);ob("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{b||(xa(a),b=a.byteLength);return a[--b]};J("random",c);J("urandom",c);F("/dev/shm");F("/dev/shm/tmp")})();
(function(){F("/proc");var a=F("/proc/self");F("/proc/self/fd");mb({Ra(){var b=Ka(a,"fd",16895,73);b.Oa={Xa:A.Oa.Xa};b.Na={sb(c,d){c=+d;var e=I(c);c={parent:null,Ra:{tb:"fake"},Na:{ub:()=>e.path},id:c+1};return c.parent=c},Ib(){return Array.from(G.entries()).filter(([,c])=>c).map(([c])=>c.toString())}};return b}},{},"/proc/self/fd")})();k.requestAnimationFrame=Nb;k.pauseMainLoop=function(){T&&(T=null,Qb++)};k.resumeMainLoop=function(){Qb++;var a=Ib,b=Jb,c=Kb;Kb=null;Zb(c,0,!1,Rb,!0);Pb(a,b);T()};
k.noExitRuntime&&(qa=k.noExitRuntime);k.print&&(da=k.print);k.printErr&&(n=k.printErr);var zc=k.preInit;if(zc)for(typeof zc=="function"&&(k.preInit=zc=[zc]);zc.length>0;)zc.shift()();
var Dc={782308:(a,b,c)=>{function d(){f.state!=="running"&&f.resume()}var e=window.AudioContext||window.webkitAudioContext;if(!e)return 0;try{var f=new e({sampleRate:a})}catch(m){f=new e}var g={};g.ctx=f;g.next=0;g.timer=0;k.__sfps_audio=g;window.addEventListener("pointerdown",d,!0);window.addEventListener("keydown",d,!0);window.addEventListener("touchstart",d,!0);var h=c*b/a;g.timer=setInterval(function(){if(f.state==="running"){var m=f.currentTime;for(g.next<m&&(g.next=m);g.next<m+h;){Ac();for(var l=
Bc()>>1,w=f.createBuffer(1,b,a),x=w.getChannelData(0),y=0;y<b;y++)x[y]=O[l+y]/32768;l=f.createBufferSource();l.buffer=w;l.connect(f.destination);l.start(g.next);g.next+=b/a}}},1E3*b/a);return 1},783419:()=>{typeof K==="undefined"||typeof D==="undefined"?Cc():lb(function(a){a&&console.warn("save not loaded: "+a);Cc()})},783613:a=>{(a=document.querySelector(a?t(M,a):""))&&a.addEventListener("contextmenu",function(b){b.preventDefault()})},783747:()=>Math.max(1,window.innerWidth|0),783794:()=>Math.max(1,
window.innerHeight|0),783842:(a,b)=>{a=a?t(M,a):"";b=b?t(M,b):"";console.error(a+": "+b);if(typeof document!=="undefined"&&document.body){var c=document.createElement("div");c.setAttribute("style","position:fixed;inset:0;z-index:9999;background:#101014;color:#e8e8ec;font:14px/1.5 monospace;padding:2rem;white-space:pre-wrap;overflow:auto");c.textContent=a+"\n\n"+b;document.body.appendChild(c)}},784295:a=>{a=a?t(M,a):"";try{F(a)}catch(b){}try{return mb(D,{qc:!0},a),1}catch(b){return console.warn("no persistent save: "+
b),0}}},Bc,Ac,Gb,Cc,Ec,Fc,Gc,R,Hc={C:function(a,b,c){ra=c;try{var d=I(a);switch(b){case 0:var e=r();if(e<0)break;for(;G[e];)e++;return jb(d,e).fb;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=r(),d.flags=d.flags&-289793|e&289792,0;case 12:return e=r(),O[e+0>>1]=2,0;case 13:case 14:return 0}return-28}catch(f){if(typeof K=="undefined"||f.name!=="ErrnoError")throw f;return-f.Wa}},W:function(a,b,c){ra=c;try{var d=I(a);switch(b){case 21509:return d.Qa?0:-59;case 21505:if(!d.Qa)return-59;
if(d.Qa.$a.Fc){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=r();q[e>>2]=25856;q[e+4>>2]=5;q[e+8>>2]=191;q[e+12>>2]=35387;for(var f=0;f<32;f++)z[e+f+17]=a[f]||0}return 0;case 21510:case 21511:case 21512:return d.Qa?0:-59;case 21506:case 21507:case 21508:if(!d.Qa)return-59;if(d.Qa.$a.Gc)for(e=r(),a=[],f=0;f<32;f++)a.push(z[e+f+17]);return 0;case 21519:if(!d.Qa)return-59;e=r();return q[e>>2]=0;case 21520:return d.Qa?-28:-59;case 21537:case 21531:e=r();if(!d.Oa.Ec)throw new v(59);
return d.Oa.Ec(d,b,e);case 21523:if(!d.Qa)return-59;d.Qa.$a.Hc&&(f=[24,80],e=r(),O[e>>1]=f[0],O[e+2>>1]=f[1]);return 0;case 21524:return d.Qa?0:-59;case 21515:return d.Qa?0:-59;default:return-28}}catch(g){if(typeof K=="undefined"||g.name!=="ErrnoError")throw g;return-g.Wa}},X:function(a,b,c,d){ra=d;try{b=b?t(M,b):"";var e=b;if(e.charAt(0)==="/")b=e;else{var f=a===-100?"/":I(a).path;if(e.length==0)throw new v(44);b=f+"/"+e}var g=d?r():0;c&64&&(g&=-19);return Qa(b,c,g).fb}catch(h){if(typeof K=="undefined"||
h.name!=="ErrnoError")throw h;return-h.Wa}},Y:()=>ka(""),S:()=>{qa=!1;sb=0},P:(a,b)=>{tb[a]&&(clearTimeout(tb[a].id),delete tb[a]);if(!b)return 0;var c=setTimeout(()=>{delete tb[a];xb(()=>Fc(a,performance.now()))},b);tb[a]={id:c,Id:b};return 0},r:(a,b,c)=>{yb.length=0;for(var d;d=M[b++];){var e=d!=105;e&=d!=112;c+=e&&c%8?4:0;yb.push(d==112?N[c>>2]:d==106?rb[c>>3]:d==105?q[c>>2]:zb[c>>3]);c+=e?8:4}return Dc[a](...yb)},Ba:()=>{throw"unwind";},O:()=>performance.now(),ra:(a,b)=>{a=P(a);return a?a.requestPointerLock?
(navigator.userActivation?navigator.userActivation.isActive:Q.Cb&&Q.$b.Xb)?Ab(a):b?(Db([a]),1):-2:-1:-4},Q:()=>{ka("OOM")},sa:(a,b,c)=>{a=P(a);if(!a)return-4;a.width=b;a.height=c;return 0},Aa:(a,b,c,d)=>Hb(a,b,c,d,2,"keydown"),za:(a,b,c,d)=>Hb(a,b,c,d,3,"keyup"),ta:(a,b,c)=>{a=R.get(a);Zb(a,b,c)},xa:(a,b,c,d)=>bc(a,b,c,d,5,"mousedown"),ya:(a,b,c,d)=>bc(a,b,c,d,8,"mousemove"),wa:(a,b,c,d)=>bc(a,b,c,d,6,"mouseup"),ua:(a,b,c,d)=>document.body?.requestPointerLock?(a=P(a))?cc(a,b,c,d):-4:-1,va:(a,b,c,
d)=>dc(a,b,c,d),Da:(a,b)=>{var c=b>>2;b={alpha:!!z[b+0],depth:!!z[b+1],stencil:!!z[b+2],antialias:!!z[b+3],premultipliedAlpha:!!z[b+4],preserveDrawingBuffer:!!z[b+5],powerPreference:sc[q[c+2]],failIfMajorPerformanceCaveat:!!z[b+12],desynchronized:!!z[b+33],Kc:q[c+4],wd:q[c+5],bc:z[b+24],yc:z[b+25],Ad:q[c+7],Hd:z[b+32]};a=P(a);return!a||b.yc?0:qc(a,b)},Ca:a=>{rc=mc[a];k.ctx=U=rc?.Vb;return!a||U?0:-5},B:function(a){try{var b=I(a);Sa(b);return 0}catch(c){if(typeof K=="undefined"||c.name!=="ErrnoError")throw c;
return c.Wa}},V:function(a,b,c,d){try{a:{var e=I(a);a=b;for(var f,g=b=0;g<c;g++){var h=N[a>>2],m=N[a+4>>2];a+=8;try{var l=e,w=h,x=m,y=f,L=z;if(x<0||y<0)throw new v(28);if(l.fb===null)throw new v(8);if((l.flags&2097155)===1)throw new v(8);if(B(l.node.mode))throw new v(31);if(!l.Oa.read)throw new v(28);var X=typeof y!="undefined";if(!X)y=l.position;else if(!l.seekable)throw new v(70);var $b=l.Oa.read(l,L,w,x,y);X||(l.position+=$b);var Ia=$b}catch(S){if(b>0&&S instanceof v&&(S.Wa==6||S.Wa==6))break;
throw S;}if(Ia<0){var ac=-1;break a}b+=Ia;if(Ia<m)break;typeof f!="undefined"&&(f+=Ia)}ac=b}N[d>>2]=ac;return 0}catch(S){if(typeof K=="undefined"||S.name!=="ErrnoError")throw S;return S.Wa}},T:function(a,b,c,d){b=b<-9007199254740992||b>9007199254740992?NaN:Number(b);try{if(isNaN(b))return 22;var e=I(a);pb(e,b,c);rb[d>>3]=BigInt(e.position);e.Mb&&!b&&c===0&&(e.Mb=null);return 0}catch(f){if(typeof K=="undefined"||f.name!=="ErrnoError")throw f;return f.Wa}},U:function(a,b,c,d){try{var e=I(a);a=b;if(c==
1)var f=Ra(e,z,N[a>>2],N[a+4>>2]);else{for(var g=b=0,h=a;g<c;g++,h+=8)b+=N[h+4>>2];var m=new Uint8Array(b);for(g=h=0;g<c;g++,a+=8){var l=N[a>>2],w=N[a+4>>2];m.set(M.subarray(l,l+w),h);h+=w}f=Ra(e,m,0,b)}N[d>>2]=f;return 0}catch(x){if(typeof K=="undefined"||x.name!=="ErrnoError")throw x;return x.Wa}},h:a=>U.activeTexture(a),x:(a,b)=>{U.attachShader(V[a],W[b])},z:(a,b)=>{a==35051?U.fd=b:a==35052&&(U.tc=b);U.bindBuffer(a,hc[b])},y:(a,b)=>{U.bindFramebuffer(a,ic[b])},pa:(a,b)=>{U.bindRenderbuffer(a,jc[b])},
e:(a,b)=>{U.bindTexture(a,kc[b])},i:a=>{U.bindVertexArray(lc[a])},k:(a,b)=>U.blendFunc(a,b),ea:(a,b,c,d)=>{c&&b?U.bufferData(a,M,d,c,b):U.bufferData(a,b,d)},da:(a,b,c,d)=>{var e=M;c&&U.bufferSubData(a,b,e,d,c)},ka:a=>U.checkFramebufferStatus(a),D:a=>U.clear(a),F:a=>{U.compileShader(W[a])},N:()=>{var a=nc(V),b=U.createProgram();b.name=a;b.Fb=b.Db=b.Eb=0;b.Ub=1;V[a]=b;return a},H:a=>{var b=nc(W);W[b]=U.createShader(a);return b},ja:(a,b)=>{for(var c=0;c<a;++c){var d=q[b+c*4>>2],e=ic[d];e&&(U.deleteFramebuffer(e),
e.name=0,ic[d]=null)}},ga:a=>{if(a){var b=V[a];b?(U.deleteProgram(b),b.name=0,V[a]=null):Y||=1281}},ia:(a,b)=>{for(var c=0;c<a;c++){var d=q[b+c*4>>2],e=jc[d];e&&(U.deleteRenderbuffer(e),e.name=0,jc[d]=null)}},q:a=>{if(a){var b=W[a];b?(U.deleteShader(b),W[a]=null):Y||=1281}},I:(a,b)=>{for(var c=0;c<a;c++){var d=q[b+c*4>>2],e=kc[d];e&&(U.deleteTexture(e),e.name=0,kc[d]=null)}},ha:(a,b)=>{for(var c=0;c<a;c++){var d=q[b+c*4>>2];U.deleteVertexArray(lc[d]);lc[d]=null}},j:a=>{U.depthMask(!!a)},b:a=>U.disable(a),
m:(a,b,c)=>{U.drawArrays(a,b,c)},d:a=>U.enable(a),u:a=>{U.enableVertexAttribArray(a)},la:(a,b,c,d)=>{U.framebufferRenderbuffer(a,b,c,jc[d])},ma:(a,b,c,d,e)=>{U.framebufferTexture2D(a,b,c,kc[d],e)},fa:(a,b)=>{oc(a,b,"createBuffer",hc)},na:(a,b)=>{oc(a,b,"createFramebuffer",ic)},qa:(a,b)=>{oc(a,b,"createRenderbuffer",jc)},p:(a,b)=>{oc(a,b,"createTexture",kc)},K:(a,b)=>{oc(a,b,"createVertexArray",lc)},J:a=>U.generateMipmap(a),$:()=>{var a=U.getError()||Y;Y=0;return a},aa:(a,b)=>uc(a,b),ca:(a,b,c,d)=>
{a=U.getProgramInfoLog(V[a]);a===null&&(a="(unknown error)");b=b>0&&d?u(a,M,d,b):0;c&&(q[c>>2]=b)},L:(a,b,c)=>{if(c)if(a>=fc)Y||=1281;else if(a=V[a],b==35716)a=U.getProgramInfoLog(a),a===null&&(a="(unknown error)"),q[c>>2]=a.length+1;else if(b==35719){if(!a.Fb){var d=U.getProgramParameter(a,35718);for(b=0;b<d;++b)a.Fb=Math.max(a.Fb,U.getActiveUniform(a,b).name.length+1)}q[c>>2]=a.Fb}else if(b==35722){if(!a.Db)for(d=U.getProgramParameter(a,35721),b=0;b<d;++b)a.Db=Math.max(a.Db,U.getActiveAttrib(a,
b).name.length+1);q[c>>2]=a.Db}else if(b==35381){if(!a.Eb)for(d=U.getProgramParameter(a,35382),b=0;b<d;++b)a.Eb=Math.max(a.Eb,U.getActiveUniformBlockName(a,b).length+1);q[c>>2]=a.Eb}else q[c>>2]=U.getProgramParameter(a,b);else Y||=1281},ba:(a,b,c,d)=>{a=U.getShaderInfoLog(W[a]);a===null&&(a="(unknown error)");b=b>0&&d?u(a,M,d,b):0;c&&(q[c>>2]=b)},E:(a,b,c)=>{c?b==35716?(a=U.getShaderInfoLog(W[a]),a===null&&(a="(unknown error)"),q[c>>2]=a?a.length+1:0):b==35720?(a=U.getShaderSource(W[a]),q[c>>2]=a?
a.length+1:0):q[c>>2]=U.getShaderParameter(W[a],b):Y||=1281},g:(a,b)=>{b=b?t(M,b):"";if(a=V[a]){var c=a,d=c.wb,e=c.nc,f;if(!d){c.wb=d={};c.mc={};var g=U.getProgramParameter(c,35718);for(f=0;f<g;++f){var h=U.getActiveUniform(c,f);var m=h.name;h=h.size;var l=vc(m);l=l>0?m.slice(0,l):m;var w=c.Ub;c.Ub+=h;e[l]=[h,w];for(m=0;m<h;++m)d[w]=m,c.mc[w++]=l}}c=a.wb;d=0;e=b;f=vc(b);f>0&&(d=parseInt(b.slice(f+1))>>>0,e=b.slice(0,f));if((e=a.nc[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||U.getUniformLocation(a,b)))return d}else Y||=
1281;return-1},Z:a=>U.lineWidth(a),M:a=>{a=V[a];U.linkProgram(a);a.wb=0;a.nc={}},oa:(a,b,c,d)=>U.renderbufferStorage(a,b,c,d),G:(a,b,c,d)=>{for(var e="",f=0;f<b;++f){var g=(g=N[c+f*4>>2])?t(M,g,d?N[d+f*4>>2]:void 0):"";e+=g}U.shaderSource(W[a],e)},o:(a,b,c,d,e,f,g,h,m)=>{if(U.tc)U.texImage2D(a,b,c,d,e,f,g,h,m);else if(m){var l=xc(h);m>>>=31-Math.clz32(l.BYTES_PER_ELEMENT);U.texImage2D(a,b,c,d,e,f,g,h,l,m)}else{if(m){l=xc(h);var w=e*(({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[g-
6402]||1)*l.BYTES_PER_ELEMENT*d+4-1&-4);m=l.subarray(m>>>31-Math.clz32(l.BYTES_PER_ELEMENT),m+w>>>31-Math.clz32(l.BYTES_PER_ELEMENT))}else m=null;U.texImage2D(a,b,c,d,e,f,g,h,m)}},_:(a,b,c)=>U.texParameterf(a,b,c),c:(a,b,c)=>U.texParameteri(a,b,c),n:(a,b)=>{U.uniform1f(yc(a),b)},a:(a,b)=>{U.uniform1i(yc(a),b)},t:(a,b,c)=>{U.uniform2f(yc(a),b,c)},s:(a,b,c)=>{b&&U.uniform3fv(yc(a),Z,c>>2,b*3)},f:(a,b,c)=>{b&&U.uniform4fv(yc(a),Z,c>>2,b*4)},l:(a,b,c,d)=>{b&&U.uniformMatrix4fv(yc(a),!!c,Z,d>>2,b*16)},
w:a=>{a=V[a];U.useProgram(a);U.uc=a},v:(a,b,c,d,e,f)=>{U.vertexAttribPointer(a,b,c,!!d,e,f)},A:(a,b,c,d)=>U.viewport(a,b,c,d),R:vb};function Ic(){var a=Ec;try{var b=a(0,0);ea=b;vb(b)}catch(c){ub(c)}}async function Jc(){fa();var a=k.setStatus;a&&(a("Running..."),await new Promise(b=>setTimeout(b,1)),setTimeout(a,1,""));p||(k.noFSInit||Za||qb(),Kc.Fa(),$a=!1,k.onRuntimeInitialized?.(),k.noInitialRun||Ic(),ia())}var Kc;
(async function(){function a(d){d=Kc=d.exports;Bc=k._audio_web_chunk=d.Ga;Ac=k._audio_web_fill=d.Ha;Gb=d.Ia;Cc=k._sfps_boot=d.Ja;Ec=k._main=d.Ka;Fc=d.Ma;Gc=d.Ea;R=d.La;d=Gc.buffer;z=new Int8Array(d);O=new Int16Array(d);M=new Uint8Array(d);wc=new Uint16Array(d);q=new Int32Array(d);N=new Uint32Array(d);Z=new Float32Array(d);zb=new Float64Array(d);rb=new BigInt64Array(d);return Kc}var b={a:Hc},c=k.instantiateWasm;if(c)return new Promise(d=>{c(b,e=>d(a(e)))});la??=k.locateFile?k.locateFile("index.wasm",
ba):ba+"index.wasm";return function(d){return a(d.instance)}(await oa(b))})().then(()=>Jc());
