/**
 * @file inflate.h
 * @brief RFC 1951 raw DEFLATE decompression, for the baked assets.
 *
 * ENGLISH
 * -------
 * The assets are 304KB of text baked into the binary, and 69% of the shipped
 * exe is that .rdata. They are also mostly base64: ASSET_SPRITES uses 66
 * distinct characters and ASSET_SOUNDS 65, so every character carries under
 * six bits in a byte that holds eight. Measured with zlib over the real baked
 * payload, deflate takes 303,791 bytes to 164,169 -- 139,622 bytes, or 29% of
 * the whole binary.
 *
 * WHY DEFLATE AND NOT SOMETHING SMALLER TO DECODE. The compressor side is
 * free: bake.ps1 calls .NET's DeflateStream, which is present in the
 * PowerShell that already runs the build and takes 23ms over the whole asset
 * set. Nothing is added to the toolchain. That makes the only cost this file,
 * and it buys 139KB where a hand-rolled LZSS with a forty-line decoder buys
 * 81KB -- the extra 59KB is what Huffman coding on top of LZ77 is worth on
 * this data.
 *
 * WHAT IT DOES NOT DO. No zlib or gzip wrapper, no checksum, no streaming: one
 * call, whole buffer in, whole buffer out. The input is generated by the build
 * that ships with the binary, so a corrupt stream is a broken build rather
 * than a hostile input -- but every read is still bounds-checked and every
 * malformed code returns an error instead of walking off a buffer.
 *
 * @note The structure follows Mark Adler's puff.c: canonical Huffman decoded
 *       by walking code lengths rather than by a lookup table. Slower per
 *       symbol and far smaller, which is the right trade for a decompressor
 *       that runs once at startup in a project measured in bytes.
 *
 * 한국어
 * ------
 * @brief 구워 넣은 에셋을 위한 RFC 1951 raw DEFLATE 압축 해제입니다.
 *
 * 에셋은 바이너리에 구워 넣은 304KB의 텍스트이며, 배포되는 exe의 69%가 그 .rdata입니다.
 * 그리고 대부분이 base64입니다. ASSET_SPRITES는 66개, ASSET_SOUNDS는 65개의 문자만
 * 사용하므로, 문자마다 8비트가 담기는 자리에 6비트 미만을 싣고 있습니다. 실제 구워진
 * 페이로드를 zlib으로 측정하면 deflate가 303,791바이트를 164,169로 줄입니다. 139,622바이트,
 * 즉 바이너리 전체의 29%입니다.
 *
 * 왜 디코드가 더 쉬운 방식이 아니라 deflate인가. 압축기 쪽이 공짜이기 때문입니다.
 * bake.ps1은 .NET의 DeflateStream을 호출하는데, 이는 이미 빌드를 실행하고 있는
 * PowerShell에 들어 있으며 전체 에셋에 23밀리초가 걸립니다. 툴체인에 추가되는 것이
 * 없습니다. 그래서 비용은 이 파일뿐이고, 그 대가로 139KB를 얻습니다. 마흔 줄짜리 디코더를
 * 가진 수제 LZSS는 81KB를 얻습니다. 그 차이 59KB가 이 데이터에서 LZ77 위에 얹은 허프만
 * 부호화의 값어치입니다.
 *
 * 하지 않는 것. zlib이나 gzip 래퍼도, 체크섬도, 스트리밍도 없습니다. 한 번의 호출로 버퍼
 * 전체가 들어가고 전체가 나옵니다. 입력은 바이너리와 함께 배포되는 빌드가 생성하므로,
 * 손상된 스트림은 적대적 입력이 아니라 망가진 빌드입니다. 그럼에도 모든 읽기는 경계를
 * 검사하고 잘못된 부호는 버퍼 밖으로 나가는 대신 오류를 반환합니다.
 *
 * @note 구조는 Mark Adler의 puff.c를 따릅니다. 정규 허프만을 조회 테이블이 아니라 부호
 *       길이를 훑어 해독합니다. 심볼당 느리고 훨씬 작은데, 바이트 단위로 측정되는
 *       프로젝트에서 시작 시 한 번 실행되는 압축 해제기에는 그쪽이 옳은 선택입니다.
 */
#ifndef INFLATE_H
#define INFLATE_H

/**
 * @brief Expands a raw DEFLATE stream into a caller-supplied buffer.
 *
 * ENGLISH
 * -------
 * @param[out] dst     Destination buffer.
 * @param[in]  dst_cap Its capacity in bytes.
 * @param[in]  src     Raw DEFLATE data -- no zlib header, no gzip header.
 * @param[in]  src_len Its length in bytes.
 * @return Bytes written, or -1 if the stream was malformed or would not fit.
 *
 * @note Writes nothing past `dst_cap`. A stream that expands to more than the
 *       caller expected is an error rather than a truncation, because the
 *       caller sized the buffer from the length the baker recorded: if the two
 *       disagree, the header and the binary were built from different assets
 *       and a half-written buffer would be parsed as if it were whole.
 *
 * 한국어
 * ------
 * @brief raw DEFLATE 스트림을 호출자가 제공한 버퍼로 펼칩니다.
 * @param[out] dst     대상 버퍼.
 * @param[in]  dst_cap 바이트 단위 용량.
 * @param[in]  src     raw DEFLATE 데이터. zlib 헤더도 gzip 헤더도 없습니다.
 * @param[in]  src_len 바이트 단위 길이.
 * @return 기록된 바이트 수. 스트림이 잘못되었거나 들어가지 않으면 -1입니다.
 *
 * @note `dst_cap`를 넘어 기록하지 않습니다. 호출자가 예상한 것보다 크게 펼쳐지는 스트림은
 *       잘라 내는 대신 오류로 처리합니다. 호출자는 베이커가 기록한 길이로 버퍼 크기를
 *       정했으므로, 둘이 어긋난다면 헤더와 바이너리가 서로 다른 에셋으로 만들어진 것이며
 *       절반만 기록된 버퍼는 온전한 것처럼 파싱됩니다.
 */
int inflate_raw(unsigned char *dst, int dst_cap,
                const unsigned char *src, int src_len);

#endif
